### ISSUE TITLE
Is possible use this to make p2p calls?

### ISSUE THREAD

**Issue by pablodgonzalez** [tgcallsjs/tgcalls#19]
I find this lib and seems is just work with chats and groups. there is a way to make calls directly to a user?

**Comment by rojvv** [comment]
Not with this library.

**Comment by pablodgonzalez** [comment]
@roj1512 Thanks for you asnwer. Do you know if there is something to do that in node?

**Comment by rojvv** [comment]
Not that I know.

**Comment by pablodgonzalez** [comment]
Thanks a lot anyway!!!

**Comment by rojvv** [comment]
Welcome.
