### ISSUE TITLE
[Question] Video Calls are implemented ?

### ISSUE THREAD

**Issue by tilibougnia** [tgcallsjs/tgcalls#5]
Hi All,

Thanks for your work. I would like to know if Video Calls are implemented ?

Moreover I'd like to participate of development.

Kind regards

**Comment by rojserbest** [comment]
They’re not.

**Comment by tilibougnia** [comment]
Ok Thanks :)

**Comment by AndrewLaneX** [comment]
The group video calls are currently only available in the closed source betas. I might try to implement it once the source code for the apps are released, but any help is appreciated.

Feel free to join our Telegram group: https://t.me/tgcallsjschat

**Comment by rojserbest** [comment]
By the way, the source codes are public now.

**Comment by AndrewLaneX** [comment]
I don't currently have time to work on tgcallsjs but I'm able to help a bit in our Telegram group: https://t.me/tgcallsjschat
